version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      vpdbr:
        ipv4_address: 10.5.0.5


  kafka-1:
    image: 'bitnami/kafka:2'
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - 'kafka_data_1:/bitnami'
#      - './props/server1.properties:/opt/bitnami/kafka/conf/server.properties'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_PORT_NUMBER=9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.6:9092,PLAINTEXT_HOST://localhost:29092
    networks:
      vpdbr:
        ipv4_address: 10.5.0.6
    depends_on:
      - zookeeper

  kafka-2:
    image: 'bitnami/kafka:2'
    ports:
      - '9093:9093'
      - '29093:29093'
    volumes:
      - 'kafka_data_2:/bitnami'
#      - './props/server2.properties:/opt/bitnami/kafka/conf/server.properties'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_PORT_NUMBER=9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,PLAINTEXT_HOST://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.7:9093,PLAINTEXT_HOST://localhost:29093
    networks:
      vpdbr:
        ipv4_address: 10.5.0.7
    depends_on:
      - zookeeper

  kafka-3:
    image: 'bitnami/kafka:2'
    ports:
      - '9094:9094'
      - '29094:29094'
    volumes:
      - 'kafka_data_3:/bitnami'
#      - './props/server3.properties:/opt/bitnami/kafka/conf/server.properties'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_PORT_NUMBER=9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,PLAINTEXT_HOST://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.5.08:9094,PLAINTEXT_HOST://localhost:29094
    networks:
      vpdbr:
        ipv4_address: 10.5.0.8
    depends_on:
      - zookeeper


volumes:
  zookeeper_data:
    driver: local
  kafka_data_1:
    driver: local
  kafka_data_2:
    driver: local
  kafka_data_3:
    driver: local

networks:
  vpdbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
